<?php

namespace Container17UAd7t;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lm9d4ah.App\Entity\Pin' shared service.
     *
     * @return \App\Entity\Pin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lm9d4ah": it references class "App\\Entity\\Pin" but no such service exists.');
    }
}
