<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container17UAd7t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container17UAd7t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container17UAd7t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container17UAd7t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container17UAd7t\App_KernelDevDebugContainer([
    'container.build_hash' => '17UAd7t',
    'container.build_id' => '31abbb98',
    'container.build_time' => 1644591200,
], __DIR__.\DIRECTORY_SEPARATOR.'Container17UAd7t');
