<?php

namespace ApiBackendBundle\Repository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFrance()
    {
        return $this->findOneByiSOCode('FR');
    }

    /**
     * @param null|object $filter
     * @return \ApiBackendBundle\Entity\Country[]
     */
    public function findAllByFilter($filter = null)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->leftJoin('c.countryLabels', 'label')
            ->leftJoin('label.lang', 'lang');

        if ($filter && is_object($filter)) {

            foreach ($filter as $k => $v) {
                if ($v != "") {
                    if ($k === 'isOrange') {
                        $qb->andWhere('c.isOrange = :' . $k)
                            ->setParameter($k, $v);
                    } else if ($k === 'lang') {
                        $qb->andWhere('lang.local = :' . $k)
                            ->setParameter($k, $v);
                    } else {
                        $qb->andWhere('c.' . $k . ' LIKE :' . $k)
                            ->setParameter($k, '%' . $v . '%');
                    }
                }
            }
        }

        if (!$filter || !$filter->lang) {
            $qb->andWhere('lang.local = :local')
                ->setParameter('local', 'fr_FR')
            ;
        }
        $qb->orderBy('label.wording', 'asc');

        return $qb->getQuery()->getResult();
    }

} // end class
